services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./static:/app/static
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: ["streamlit", "run", "app.py", "--server.port=8501"]